/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthRouteImport } from './routes/health'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as MovesRouteImport } from './routes/moves'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as PipeRouteImport } from './routes/pipe'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as HoldingsIdRouteImport } from './routes/holdings.$id'
import { Route as HuntersIdRouteImport } from './routes/hunters.$id'
import { Route as IssuesIndexRouteImport } from './routes/issues.index'
import { Route as IssuesIdRouteImport } from './routes/issues.$id'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffIdRouteImport } from './routes/staff.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const MovesRoute = MovesRouteImport.update({
  id: '/moves',
  path: '/moves',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const PipeRoute = PipeRouteImport.update({
  id: '/pipe',
  path: '/pipe',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const HoldingsIdRoute = HoldingsIdRouteImport.update({
  id: '/holdings/$id',
  path: '/holdings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HuntersIdRoute = HuntersIdRouteImport.update({
  id: '/hunters/$id',
  path: '/hunters/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIndexRoute = IssuesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IssuesRoute,
} as any)
const IssuesIdRoute = IssuesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => IssuesRoute,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffIdRoute = StaffIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StaffRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/issues': typeof IssuesRouteWithChildren
  '/moves': typeof MovesRoute
  '/office': typeof OfficeRoute
  '/pipe': typeof PipeRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRouteWithChildren
  '/trends': typeof TrendsRoute
  '/holdings/$id': typeof HoldingsIdRoute
  '/hunters/$id': typeof HuntersIdRoute
  '/issues/$id': typeof IssuesIdRoute
  '/staff/$id': typeof StaffIdRoute
  '/issues/': typeof IssuesIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/moves': typeof MovesRoute
  '/office': typeof OfficeRoute
  '/pipe': typeof PipeRoute
  '/settings': typeof SettingsRoute
  '/trends': typeof TrendsRoute
  '/holdings/$id': typeof HoldingsIdRoute
  '/hunters/$id': typeof HuntersIdRoute
  '/issues/$id': typeof IssuesIdRoute
  '/staff/$id': typeof StaffIdRoute
  '/issues': typeof IssuesIndexRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/issues': typeof IssuesRouteWithChildren
  '/moves': typeof MovesRoute
  '/office': typeof OfficeRoute
  '/pipe': typeof PipeRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRouteWithChildren
  '/trends': typeof TrendsRoute
  '/holdings/$id': typeof HoldingsIdRoute
  '/hunters/$id': typeof HuntersIdRoute
  '/issues/$id': typeof IssuesIdRoute
  '/staff/$id': typeof StaffIdRoute
  '/issues/': typeof IssuesIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/issues'
    | '/moves'
    | '/office'
    | '/pipe'
    | '/settings'
    | '/staff'
    | '/trends'
    | '/holdings/$id'
    | '/hunters/$id'
    | '/issues/$id'
    | '/staff/$id'
    | '/issues/'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/moves'
    | '/office'
    | '/pipe'
    | '/settings'
    | '/trends'
    | '/holdings/$id'
    | '/hunters/$id'
    | '/issues/$id'
    | '/staff/$id'
    | '/issues'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/issues'
    | '/moves'
    | '/office'
    | '/pipe'
    | '/settings'
    | '/staff'
    | '/trends'
    | '/holdings/$id'
    | '/hunters/$id'
    | '/issues/$id'
    | '/staff/$id'
    | '/issues/'
    | '/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  IssuesRoute: typeof IssuesRouteWithChildren
  MovesRoute: typeof MovesRoute
  OfficeRoute: typeof OfficeRoute
  PipeRoute: typeof PipeRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRouteWithChildren
  TrendsRoute: typeof TrendsRoute
  HoldingsIdRoute: typeof HoldingsIdRoute
  HuntersIdRoute: typeof HuntersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moves': {
      id: '/moves'
      path: '/moves'
      fullPath: '/moves'
      preLoaderRoute: typeof MovesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipe': {
      id: '/pipe'
      path: '/pipe'
      fullPath: '/pipe'
      preLoaderRoute: typeof PipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holdings/$id': {
      id: '/holdings/$id'
      path: '/holdings/$id'
      fullPath: '/holdings/$id'
      preLoaderRoute: typeof HoldingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hunters/$id': {
      id: '/hunters/$id'
      path: '/hunters/$id'
      fullPath: '/hunters/$id'
      preLoaderRoute: typeof HuntersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/': {
      id: '/issues/'
      path: '/'
      fullPath: '/issues/'
      preLoaderRoute: typeof IssuesIndexRouteImport
      parentRoute: typeof IssuesRoute
    }
    '/issues/$id': {
      id: '/issues/$id'
      path: '/$id'
      fullPath: '/issues/$id'
      preLoaderRoute: typeof IssuesIdRouteImport
      parentRoute: typeof IssuesRoute
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/$id': {
      id: '/staff/$id'
      path: '/$id'
      fullPath: '/staff/$id'
      preLoaderRoute: typeof StaffIdRouteImport
      parentRoute: typeof StaffRoute
    }
  }
}

interface IssuesRouteChildren {
  IssuesIdRoute: typeof IssuesIdRoute
  IssuesIndexRoute: typeof IssuesIndexRoute
}

const IssuesRouteChildren: IssuesRouteChildren = {
  IssuesIdRoute: IssuesIdRoute,
  IssuesIndexRoute: IssuesIndexRoute,
}

const IssuesRouteWithChildren =
  IssuesRoute._addFileChildren(IssuesRouteChildren)

interface StaffRouteChildren {
  StaffIdRoute: typeof StaffIdRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffIdRoute: StaffIdRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  IssuesRoute: IssuesRouteWithChildren,
  MovesRoute: MovesRoute,
  OfficeRoute: OfficeRoute,
  PipeRoute: PipeRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRouteWithChildren,
  TrendsRoute: TrendsRoute,
  HoldingsIdRoute: HoldingsIdRoute,
  HuntersIdRoute: HuntersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
